spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?useTimezone=true&serverTimezone=UTC
    username: postgres
    password: hahn
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
